import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
import Loading from "@/app/loading";
import PrelineScript from "@/components/PrelineScript";
import { Suspense } from "react";
import { Toaster, toast } from 'sonner'
import { SpeedInsights } from '@vercel/speed-insights/next';
const poppins = Poppins({ weight: ['400', '700'],
style: ['normal', 'italic'],
subsets: ['latin'],
display: 'swap' });

export const metadata: Metadata = {
  title: "AE MANGA",
  description: "Generated by NextJS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Suspense fallback={<Loading />}>
          <Header />
        </Suspense>       
        <Suspense fallback={<Loading />}> {children} </Suspense>
        <SpeedInsights />
        <Toaster richColors position="top-right"/>
        <Footer/>
        <PrelineScript/>
      </body>
    </html>
  );
}
